# Generated by Django 6.0.5 on 2026-06-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('order_completed', 'Заказ'), ('menu_changed', 'Меню'), ('role_changed', 'Смена роли')], max_length=50),
        ),
    ]
