# Generated by Django 6.0.5 on 2026-06-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_analyticsevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('order_completed', 'Заказ'), ('menu_changed', 'Меню'), ('role_changed', 'Смена роли'), ('chat_message', 'Сообщение в чате')], max_length=50),
        ),
    ]
